# ...........................................................................
# generate_std_compat.cmake
# ...........................................................................
#
# USAGE:
#   cmake -DMODE=<mode> [-DDRY_RUN=ON] -P module/generate_std_compat.cmake
#
# MODES:
#   check             - Scan consumer files for unprotected standard includes.
#   generate-headers  - Create/refresh wrapper headers in include/asio/detail/std/.
#   update-includes   - Replace <header> with "asio/detail/std/header.hpp" in consumers.
#   update-content    - Alias for generate-headers (idempotent content refresh).
#   generate          - Combined: generate-headers + update-includes.
#   revert            - Combined: revert-includes + remove-headers.
#   revert-includes   - Restore raw <header> includes in consumers.
#   remove-headers    - Delete generated wrapper headers and the detail/std/ directory.
#
# OPTIONS:
#   -DDRY_RUN=ON      - Simulate actions without modifying files.
#                       (Also supports -DDRY_MODE=ON or -DDRYRUN=ON).
#
# ...........................................................................
# Copyright (c) 2026 E. Can Özen (oezen.ce [at] gmail [dot] com)
# ...........................................................................

cmake_minimum_required(VERSION 3.20)

# ---------------------------------------------------------------------------
# Dry-run Flag Robustness (supports aliases to prevent accidental typos)
# ---------------------------------------------------------------------------
if(DRY_RUN OR DRY_MODE OR DRYRUN)
    set(IS_DRY_RUN ON)
    message(STATUS "!!! DRY RUN ENABLED !!! (No physical changes will be made)")
else()
    set(IS_DRY_RUN OFF)
endif()

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Root of the asio source tree (this script lives in module/)
get_filename_component(ASIO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(STD_DIR "${ASIO_ROOT}/include/asio/detail/std")
set(INCLUDE_DIR "${ASIO_ROOT}/include/asio")

# Standard C++ headers that MUST be included for macros (import std; does not provide macros)
set(MACRO_STD_HEADERS
    cassert
    cerrno
    cfloat
    climits
    csetjmp
    csignal
    cstdarg
    cstdint
    ctime
    cwchar
    version
)

# Standard C++ headers used in asio (keep sorted)
set(STD_HEADERS
    algorithm
    any
    array
    atomic
    cassert
    cctype
    cerrno
    chrono
    climits
    codecvt
    concepts
    condition_variable
    coroutine
    csignal
    cstdarg
    cstddef
    cstdint
    cstdio
    cstdlib
    cstring
    deque
    exception
    functional
    future
    iosfwd
    istream
    iterator
    limits
    list
    locale
    memory
    mutex
    new
    optional
    ostream
    source_location
    sstream
    stdexcept
    streambuf
    string
    string_view
    system_error
    thread
    tuple
    type_traits
    typeinfo
    utility
    variant
    vector
    version
)

# ---------------------------------------------------------------------------
# Wrapper header template
# ---------------------------------------------------------------------------

set(WRAPPER_TEMPLATE [[//
// detail/std/@HEADER@.hpp
// @TILDE_LINE@
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
// auto-generated by generate_std_compat.cmake

#if !defined(ASIO_MODULE)
// Traditional (header-only) path.
# ifndef ASIO_DISABLE_STD_INCLUDES
#  ifndef ASIO_STD_@HEADER_UPPER@_NO_INCLUDE
#   include <@HEADER@>
#  endif
# endif
#else
// Module path.
# if defined(ASIO_HAS_IMPORT_STD) && !defined(ASIO_IN_GMF) && !defined(ASIO_IN_MODULE_PURVIEW)
import std;
# endif
# if defined(ASIO_IN_GMF)
#  ifndef ASIO_DISABLE_STD_INCLUDES
#   ifndef ASIO_STD_@HEADER_UPPER@_NO_INCLUDE
#    if !defined(ASIO_HAS_IMPORT_STD) || @IS_MACRO_HEADER@
#     include <@HEADER@>
#    endif
#   endif
#  endif
# endif
#endif
]])

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Generate a tilde line of given length
function(make_tilde_line header out_var)
    string(LENGTH "${header}" header_len)
    math(EXPR tilde_count "${header_len} + 18") # len("detail/std/") + len(".hpp") + 3 extra
    set(tildes "")
    foreach(i RANGE 1 ${tilde_count})
        string(APPEND tildes "~")
    endforeach()
    set(${out_var} "${tildes}" PARENT_SCOPE)
endfunction()

# Collect all .hpp and .ipp files under include/asio/, excluding detail/std/
function(collect_source_files out_var)
    file(GLOB_RECURSE all_files
        "${INCLUDE_DIR}/*.hpp"
        "${INCLUDE_DIR}/*.ipp"
    )
    set(filtered "")
    foreach(f ${all_files})
        string(FIND "${f}" "/detail/std/" pos)
        if(pos EQUAL -1)
            list(APPEND filtered "${f}")
        endif()
    endforeach()
    set(${out_var} "${filtered}" PARENT_SCOPE)
endfunction()

# Idempotent file write: only writes if content differs
function(write_if_changed file_path content)
    set(existing_content "")
    if(EXISTS "${file_path}")
        file(READ "${file_path}" existing_content)
    endif()

    if(NOT "${content}" STREQUAL "${existing_content}")
        if(IS_DRY_RUN)
            message(STATUS "  [dry-run] Would update: ${file_path}")
        else()
            file(WRITE "${file_path}" "${content}")
            message(STATUS "  Updated: ${file_path}")
        endif()
    endif()
endfunction()

# ---------------------------------------------------------------------------
# ATOMIC MODES
# ---------------------------------------------------------------------------

# MODE: check - Find unprotected standard includes
function(do_check)
    message(STATUS "=== Checking for raw standard library includes ===")
    collect_source_files(source_files)
    set(found_any OFF)

    foreach(src ${source_files})
        file(READ "${src}" content)
        # Match #include <header>
        string(REGEX MATCHALL "#[ \t]*include[ \t]*<([^>]+)>" matches "${content}")
        foreach(match ${matches})
            string(REGEX REPLACE "#[ \t]*include[ \t]*<([^>]+)>" "\\1" header "${match}")
            
            # Check if it's in our STD_HEADERS list
            list(FIND STD_HEADERS "${header}" idx)
            if(NOT idx EQUAL -1)
                file(RELATIVE_PATH rel "${ASIO_ROOT}" "${src}")
                message(WARNING "  Found raw include <${header}> in ${rel}")
                set(found_any ON)
            endif()
        endforeach()
    endforeach()

    if(NOT found_any)
        message(STATUS "  No raw standard includes found. Migration looks complete.")
    endif()
endfunction()

# MODE: generate-headers - Create detail/std/*.hpp
function(do_generate_headers)
    message(STATUS "=== Generating wrapper headers ===")
    if(NOT IS_DRY_RUN)
        file(MAKE_DIRECTORY "${STD_DIR}")
    endif()

    foreach(header ${STD_HEADERS})
        set(out_file "${STD_DIR}/${header}.hpp")
        make_tilde_line("${header}" tilde_line)
        string(TOUPPER "${header}" header_upper)
        
        set(is_macro "0")
        list(FIND MACRO_STD_HEADERS "${header}" idx)
        if(NOT idx EQUAL -1)
            set(is_macro "1")
        endif()

        string(REPLACE "@HEADER@" "${header}" content "${WRAPPER_TEMPLATE}")
        string(REPLACE "@HEADER_UPPER@" "${header_upper}" content "${content}")
        string(REPLACE "@TILDE_LINE@" "${tilde_line}" content "${content}")
        string(REPLACE "@IS_MACRO_HEADER@" "${is_macro}" content "${content}")

        write_if_changed("${out_file}" "${content}")
    endforeach()

    # Generate central all.hpp
    set(all_hpp_file "${STD_DIR}/all.hpp")
    set(all_hpp_content "//\n// detail/std/all.hpp\n// ~~~~~~~~~~~~~~~~~~~\n//\n")
    string(APPEND all_hpp_content "// auto-generated by generate_std_compat.cmake\n\n")
    string(APPEND all_hpp_content "#ifndef ASIO_DETAIL_STD_ALL_HPP\n#define ASIO_DETAIL_STD_ALL_HPP\n\n")
    foreach(header ${STD_HEADERS})
        string(APPEND all_hpp_content "#include \"asio/detail/std/${header}.hpp\"\n")
    endforeach()
    string(APPEND all_hpp_content "\n#endif // ASIO_DETAIL_STD_ALL_HPP\n")
    
    write_if_changed("${all_hpp_file}" "${all_hpp_content}")
endfunction()

# MODE: update-includes - Replace <header> with "asio/detail/std/header.hpp"
function(do_update_includes)
    message(STATUS "=== Updating consumer includes ===")
    collect_source_files(source_files)
    set(modified_count 0)

    foreach(src ${source_files})
        file(READ "${src}" content)
        set(original "${content}")

        foreach(header ${STD_HEADERS})
            string(FIND "${content}" "<${header}>" pos)
            if(NOT pos EQUAL -1)
                string(REGEX REPLACE
                    "(#[ \t]*include[ \t]+)<${header}>"
                    "\\1\"asio/detail/std/${header}.hpp\""
                    content "${content}"
                )
            endif()
        endforeach()

        if(NOT "${content}" STREQUAL "${original}")
            file(RELATIVE_PATH rel "${ASIO_ROOT}" "${src}")
            if(IS_DRY_RUN)
                message(STATUS "  [dry-run] Would update: ${rel}")
            else()
                file(WRITE "${src}" "${content}")
                message(STATUS "  Updated: ${rel}")
            endif()
            math(EXPR modified_count "${modified_count} + 1")
        endif()
    endforeach()
    message(STATUS "  Processed consumer files. Modified: ${modified_count}")
endfunction()

# MODE: revert-includes - Restore <header>
function(do_revert_includes)
    message(STATUS "=== Reverting consumer includes ===")
    collect_source_files(source_files)
    set(modified_count 0)

    foreach(src ${source_files})
        file(READ "${src}" content)
        set(original "${content}")

        foreach(header ${STD_HEADERS})
            string(FIND "${content}" "\"asio/detail/std/${header}.hpp\"" pos)
            if(NOT pos EQUAL -1)
                string(REGEX REPLACE
                    "(#[ \t]*include[ \t]+)\"asio/detail/std/${header}\\.hpp\""
                    "\\1<${header}>"
                    content "${content}"
                )
            endif()
        endforeach()

        if(NOT "${content}" STREQUAL "${original}")
            file(RELATIVE_PATH rel "${ASIO_ROOT}" "${src}")
            if(IS_DRY_RUN)
                message(STATUS "  [dry-run] Would revert: ${rel}")
            else()
                file(WRITE "${src}" "${content}")
                message(STATUS "  Reverted: ${rel}")
            endif()
            math(EXPR modified_count "${modified_count} + 1")
        endif()
    endforeach()
    message(STATUS "  Reverted ${modified_count} files.")
endfunction()

# MODE: remove-headers - Delete detail/std/*.hpp
function(do_remove_headers)
    message(STATUS "=== Removing wrapper headers ===")
    if(NOT EXISTS "${STD_DIR}")
        message(STATUS "  Directory ${STD_DIR} does not exist. Nothing to do.")
        return()
    endif()

    file(GLOB all_wrappers "${STD_DIR}/*.hpp")
    set(removed_count 0)
    foreach(f ${all_wrappers})
        if(IS_DRY_RUN)
            message(STATUS "  [dry-run] Would remove: ${f}")
        else()
            file(REMOVE "${f}")
            message(STATUS "  Removed: ${f}")
        endif()
        math(EXPR removed_count "${removed_count} + 1")
    endforeach()
    
    if(NOT IS_DRY_RUN)
        file(REMOVE_RECURSE "${STD_DIR}")
        message(STATUS "  Removed directory: ${STD_DIR}")
    endif()
    message(STATUS "  Removed ${removed_count} files.")
endfunction()

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if(NOT DEFINED MODE)
    message(FATAL_ERROR "MODE not defined (check, generate-headers, update-includes, generate, revert, etc.)")
endif()

if(MODE STREQUAL "check")
    do_check()
elseif(MODE STREQUAL "generate-headers" OR MODE STREQUAL "update-content")
    do_generate_headers()
elseif(MODE STREQUAL "update-includes")
    do_update_includes()
elseif(MODE STREQUAL "generate" OR MODE STREQUAL "update")
    do_generate_headers()
    do_update_includes()
elseif(MODE STREQUAL "revert")
    do_revert_includes()
    do_remove_headers()
elseif(MODE STREQUAL "revert-includes")
    do_revert_includes()
elseif(MODE STREQUAL "remove-headers")
    do_remove_headers()
else()
    message(FATAL_ERROR "Unknown MODE: ${MODE}")
endif()
