//
// detail/std/cerrno.hpp
// ~~~~~~~~~~~~~~~~~~~~~~~~
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
// auto-generated by module_compat.cmake

#if !defined(ASIO_MODULE)
// traditional (header-only) path.
# ifndef ASIO_DISABLE_STD_INCLUDES
#  ifndef ASIO_STD_CERRNO_NO_INCLUDE
#   include <cerrno>
#  endif
# endif
#else
// module path.
# if defined(ASIO_HAS_IMPORT_STD) && !defined(ASIO_IN_GMF) && !defined(ASIO_IN_MODULE_PURVIEW)
import std;
# endif
# if defined(ASIO_IN_GMF)
#  ifndef ASIO_DISABLE_STD_INCLUDES
#   ifndef ASIO_STD_CERRNO_NO_INCLUDE
#    if !defined(ASIO_HAS_IMPORT_STD) || 1
#     include <cerrno>
#    endif
#   endif
#  endif
# endif
#endif
