name: Clang

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        version: [21, 22]
        cxx_config:
          - { std: 20, import_std: "OFF" }
          - { std: 23, import_std: "ON" }

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/clang${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }

      - name: Install libssl-dev
        run: apt-get update -qq && apt-get install -y -qq libssl-dev

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          # compiler: llvm-${{ matrix.version }}
          cmake: 4.2.3
          ninja: 1.13.0
          gcovr: true

      - name: Configure CMake
        env:
          CXX: clang++
          PATH: $HOME/.local/bin:$PATH
        run: cmake --preset linux-clang -D CMAKE_CXX_STANDARD=${{ matrix.cxx_config.std }} -D ASIO_IMPORT_STD=${{ matrix.cxx_config.import_std }}

      - name: Build
        env:
          PATH: $HOME/.local/bin:$PATH
        run: cmake --build --preset linux-clang-release

      - name: Test
        env:
          PATH: $HOME/.local/bin:$PATH
        run: ctest --preset linux-clang-release
